### ISSUE TITLE
Site has to be single page

### ISSUE THREAD

**Issue by Diacius** [Diacius/Setting-Up-A-Homelab#2]
## Due to the really weird way Jekyll built in links work this site needs to be single page
@jacobhq any ideas

**Comment by jacobhq** [comment]
@Diacius you can just create another markdown file, and gh pages will serve it. You can also put html in markdown.

**Comment by Diacius** [comment]
Yeah the problem is that relative links are broken. I'll close this now because i dont like GHPages anyway

**Comment by Diacius** [comment]
Yeah the problem is that relative links are broken. I'll close this now because i dont like GHPages anyway
